language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t acasado/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true acasado/docker-react npm run test -- --coverage